sudo: required
services:
  - docker
before_install:
  - docker build -t vasim38/docker-react -f Dockerfile.dev .

script:
  - docker run vasim38/docker-react npm run test -- --coverage
deploy:--
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-cicd"
  env: "DockerCicd-env"
  bucket_name: "elasticbeanstalk-us-east-1-484214507756"
  bucket_path: "docker-cicd" # First time it should be same as app name
  on:
    branch: master
  access_key_id: AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
